version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/travel-agency-app.jar
  discard-paths: yes